### ISSUE TITLE
Incorrect numbering in ordered lists

### ISSUE THREAD

**Issue by ansysic** [ShipBit/slickgpt#22]
Numbered lists don't go higher than 1. Also spacing between is off.

Example:
![image](https://user-images.githubusercontent.com/5899228/228568889-2d2b20e3-434f-455e-bafe-d2f8b140a798.png)

**Comment by Shackless** [comment]
@ansysic Could you please share this chat and paste the share URL here for easier debugging?

**Comment by Shackless** [comment]
Thanks for the clarification. The problem is that there are some linebreaks in the completion that our Markdown parser (mis)interprets as different list entities. This is a bit fiddly to fix and might have side effects on other completions. Because we have a workaround (asking for a list explicitly), I'd also consider this a low priority issue. I'll leave the issue open in case somebody wants to give it a shot and for documentation purposes.

**Comment by jondcoleman** [comment]
It seems to sometimes still do this when I ask for a list.
<img width="907" alt="image" src="https://user-images.githubusercontent.com/11843663/233475605-917ecd61-5a4f-41cd-bd3e-c6b02a0c626a.png">

**Comment by Shackless** [comment]
@jondcoleman 
Now that there is a "pipe" in place (see https://github.com/ShipBit/slickgpt/issues/44#issuecomment-1511629508), one could try to reformat the broken lists. My guess is that the markdown list items in these error cases contain line breaks that lead to several lists being rendered by our markdown parser.

**Comment by GrAndAG** [comment]
It seems it simply does not respect the numbers if the list items and always renders them as "1". 
I noticed that when I asked AI to continue and in the anaswer the list started not from "1" _(the list contunues the one from previous answer)_. Or if list items has some non-plain text blocks _(code blocks, for example)_.

For example, I have the reduced answer _(shortened the text and removed code blocks content, but keep `\n` in place)_ from AI _(I'm using SlickGPT with local LM_Studio server, so the response below retreived from its console)_:
```json
{
  "role": "assistant",
  "content": "Here are a few more ways to test:\n\n4. **Scan-based testing**: In this approach...\n\nExample:\n```...```\n5. **Boundary-scan testing**: In this approach...\n\nExample:\n```...```\n6. **Structural testing**: In this approach...\n\nExample:\n```...```\nThese are just a few more examples...."
}
```
And this response is rendered as 1... 1... 1. list instead of 4... 5... 6.
