### ISSUE TITLE
Iphone 7 IOS 15.7.3  - safari browser

### ISSUE THREAD

**Issue by imranaalam** [ShipBit/slickgpt#52]
streaming response not working in Iphone 7 IOS 15.7.3  - safari browser. 

it may work with json reponse.

i have tried to test it using my own python code. it ndont work either.
@app.post('/chatgpt-proxy')
async def chatgpt_proxy(request: Request):
  try:
    data = await request.json()
  except json.JSONDecodeError:
    raise HTTPException(status_code=400, detail="Invalid or empty JSON request body")

  headers = {
        'Authorization': f'Bearer {OPENAI_API_KEY}',
        'Content-Type': 'application/json',
  }
  print(data)
  print(headers)
  r = requests.post(OPENAI_API_URL, headers=headers, json=data, stream=True)
  return StreamingResponse(r.iter_content(chunk_size=8192), status_code=r.status_code)

**Comment by Shackless** [comment]
For your example code: If you're using the /chat/completion endpoint and set `stream = true`, it returns type `text/eventstream` instead of `application/json`. 
As for SlickGPT: iPhone 7 is out of maintenance and stuck on iOS 15 while we're already at iOS 16 and a new Safari version rolled out with that. I currently don't have any plans to support legacy iOS versions, sorry.
