### ISSUE TITLE
Seeing a lot of crashes mid thread

### ISSUE THREAD

**Issue by Arro** [ShipBit/slickgpt#91]
More and more frequently, I send a prompt, it starts responding, then dies right as it's about to add the completed response to the output.  So the last message in the list will be my question the LLM.  

Once randomly a few days ago, I saw that missing response in a different thread, but only for a short moment.  Then it disappeared.

I will update this issue next time it happens with any errors I see in the developer console.   I have yet to do that.

**Comment by xmoiduts** [comment]
Also ran into this issue recently.

**Comment by Shackless** [comment]
It probably either means that the API endpoint (hello, OpenAI!) is timing out or throwing errors or that your internet connection broke. The response is a stream...

**Comment by xmoiduts** [comment]
It may not delete the unfinished API response but stuck somewhere. From my usage experience, the disappeared response will show eventually, but may not in the identical session, maybe in another slickgpt chat session. Once the popped up message is so sudden that the entire session context jumped to the other session while I was typing. (hopes it is not some session-switching shortcuts)

**Comment by Shackless** [comment]
We are about to release a new major release that will change things: 
- We'll be offering fixed-price access to the OpenAI API using our Azure infrastructure. It's a lot faster than direct access (probably because Microsoft has special deals with OpenAI?). I haven't seen the problem there yet. 
- The Svelte endpoint layer will be completely removed. So even if you don't use that, there's one less point of failure because the client will be talking directly to OpenAI. Maybe that will help as well.

Stay tuned, it's coming soon.
