### ISSUE TITLE
Option to set API endpoint

### ISSUE THREAD

**Issue by xmoiduts** [ShipBit/slickgpt#94]
[This suggestion may be very immature, but I still put it here.]

Currently, more GenAI providers are emerging, followed by aggregate API providers. They may use OpenAI-compatible API schemes to simplify the integration process to other competitor Chat AI models. 

Though simplified, an API endpoint other than OpenAI is still needed. By providing the ability to set API endpoint, this GPT shell may have the possibility to directly access other Gen AI platforms.

Example: https://api.<custom-website>.<tld>/v1/chat/completions

This capability should be a client-side functionality by providing an input box and let user to input model definitions using the openai.ts-like scheme plus endpoint setting, and be merged with slickgpt-provided model choices on the browser.

Example: https://api.<custom-website>.<tld>/v1/chat/completions

**Comment by Shackless** [comment]
We kind of added this with the different providers we have now. You could use it as base for more like OpenRouter etc. but I think the current selection is sufficient for public SlickGPT. 

We have all of this (including connections to local LLMs) in [Wingman AI](https://github.com/ShipBit/wingman-ai) if you're interested in that. This can't be done with the public/hosted version of SlickGPT because it obviously can't connect to your localhost. But I am using a local version of SlickGPT to do that, too.
